# Generated by Django 3.2.9 on 2021-11-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('symbol', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('exch', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.portfolio')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.symbols')),
            ],
        ),
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.symbols')),
                ('date', models.DateField()),
                ('ebitda', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('grossProfits', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('freeCashflow', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('totalCash', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('totalRevenue', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('totalDebt', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('sharesOutstanding', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('netIncomeToCommon', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('averageVolume', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ('averageVolume10days', models.DecimalField(decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ratios',
            fields=[
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.symbols')),
                ('date', models.DateField()),
                ('profitMargins', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('grossMargins', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('operatingMargins', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('ebitdaMargins', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('returnOnAssets', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('returnOnEquity', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('forwardEps', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('trailingEps', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('forwardPE', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('trailingPE', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('quickRatio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('currentRatio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('beta', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('debtToEquity', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('payoutRatio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('priceToBook', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('shortRatio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('pegRatio', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('revenuePerShare', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('revenueGrowth', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('earningsGrowth', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('totalCashPerShare', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ret', models.DecimalField(decimal_places=6, max_digits=10)),
                ('volume', models.IntegerField()),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='chat.symbols')),
            ],
            options={
                'unique_together': {('symbol', 'date', 'time')},
            },
        ),
    ]
