# Generated by Django 3.2.9 on 2021-11-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('symbol', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=18)),
                ('high', models.DecimalField(decimal_places=4, max_digits=18)),
                ('low', models.DecimalField(decimal_places=4, max_digits=18)),
                ('Close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
